### PR TITLE
add instructions to bottom of captcha

### PR DESCRIPTION
**Pull request by QuercusFelis**
Adds some BOTTOM TEXT to give explicit instructions from the start. Intended to be helpful to first time users. Will make a way to disable this from a config.

### CODE REVIEW

**Comment by QuercusFelis** [comment]
ddddee

**Comment by QuercusFelis** [comment]
element.classList.add("style");
"Click and hold on correct fish for 2 seconds to pass captcha!"

**Comment by QuercusFelis** [comment]
image

**Comment by Yam-s** [comment]
Looks good, thanks for adding a class to it!

**Pull request merged**
